export const suggestions = [
  "Bumper-to-Bumper",
  "Original Like",
  "New Authorized",
  "Workshop Maintained",
  "Complete Service History",
  "Fresh Import",
  "Price Negotiable",
  "Alloy Rims",
  "Original Book",
  "Duplicate Book",
  "Complete Original File",
  "File Duplicate ",
  "Duplicate Number Plate",
  "Non Accidental Car",
  "New Tires",
  "Auction Sheet Available",
  "Token or Tax Up to Date",
  "Lifetime Token Paid ",
  "Urgent Sale",
  "Driven on Petrol",
  "Factory Fitted CNG",
  "Army Officer Car",
  "Minor Touch Ups",
  "Engine Repaired",
  "Sealed Engine",
  "Engine Swapped",
  "Contact During Office Hours",
  "Exchange Possible",
];
